version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  pipeline:
    executor: node/default 
    steps:
      - checkout
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm test
          name: Run tests
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  main-workflow:
    jobs:
      - pipeline